- hosts: docker

  tasks:
  - name: stop container
    command: docker stop registerapp

  - name: remove container
    command: docker rm registerapp

  - name: create container
    command: docker run -d --name registerapp -p 8080:8080 kamleshmerugu/regapp:latest
